# Generated by Django 4.2.4 on 2023-08-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_mate',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to='media/pictures'),
        ),
    ]
